### ISSUE TITLE
Certificate and vulnerabilities on mconf.rnp.br

### ISSUE THREAD

**Issue by mconf-daileon** [mconf-rnp/mconf-web#60]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1514, http://dev.mconf.org/redmine/issues/1514

---

See: https://sslcheck.globalsign.com/en_US/sslcheck/?host=mconf.rnp.br#200.130.35.223-cert-reg-srv-misc-ssl

We should try to solve as many of these vulnerabilities as possible on mconf.rnp.br. If possible, apply the changes not only in this server but on the config files and source code on the repository.

**Comment by daronco** [comment]
These are all mostly solved in the base Mconf-Web. The issues we still see are mostly related to the load balancer that serves Mconf-Web.
