### ISSUE TITLE
Disabled users lose their institution

### ISSUE THREAD

**Issue by mconf-daileon** [mconf-rnp/mconf-web#68]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1796, http://dev.mconf.org/redmine/issues/1796

---

Disabling a user also removes the link between the user and his institution. 
This is bad, because most of the times the users are automatically linked to an institution when registering. Removing the link between the user and the institution makes it hard to enable the user again in the future.

Disabled users should still lose access to the website, their memberships in spaces, etc, but they should still be linked to the their institution.

**Comment by daronco** [comment]
Migrated to `mconftec/mconf-web-rnp`.
