### ISSUE TITLE
Store institution recording quotas as NULL when they are not specified

### ISSUE THREAD

**Issue by mconf-daileon** [mconf-rnp/mconf-web#69]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1861, http://dev.mconf.org/redmine/issues/1861

---

When no quota is specified for an institution's recording quota, it is currently being stored as "0" in the database. It could be stored as NULL, so that users have the option of effectively setting it to zero to block users from recording.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Lucas Zawacki** (Lucas Zawacki)
Original Date: 2015-12-07T19:52:27Z

---

I don't see the difference between this and the way it works now. If the quota is zero and we test for disk_usage >= disk_quota it'll block recording already.

**Comment by daronco** [comment]
@lfzawacki aren't there three 3 cases?

* No quota set: will always be able to record
* Quota set to zero: will never be able to record
* Quota set to something bigger than zero: can record until the quota is reached

**Comment by daronco** [comment]
Migrated to `mconftec/mconf-web-rnp`.
