### ISSUE TITLE
Institution admins should not be able to change passwords of users that don't use local auth

### ISSUE THREAD

**Issue by mconf-daileon** [mconf-rnp/mconf-web#72]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1870, http://dev.mconf.org/redmine/issues/1870

---

Global administrators are not anymore able to change passwords for users that don't use local authentication, including themselves if that's the case (#1859).
However, institution admins are still able to update the password of users of their institution even if these users don't use the local authentication.

**Comment by daronco** [comment]
Migrated to `mconftec/mconf-web-rnp`.
