### ISSUE TITLE
The user limit in institutions should also be applied to global administrators

### ISSUE THREAD

**Issue by mconf-daileon** [mconf-rnp/mconf-web#75]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1941, http://dev.mconf.org/redmine/issues/1941

---

When setting a user limit in an institutions, admins of that institution will not be able to approve users after the limit is reached.
Global admins, however, can always approve users, even if the limit was reached.

This should be changed so that the limit also applies to global admins. It makes the values more consistent and generates less doubts, since the limit should never be surpassed.
And global admins will always be able to increase the user limit of an institution in case they really need to approve more people.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2016-04-11T15:22:56Z

---

It's important to also notice that admins can change the institution of a user. So the limits (limit of users, limit of users that can record) should also be checked when the user's institution is changing, not only when the user is being approved or when the record flag is being set.

**Comment by daronco** [comment]
Migrated to `mconftec/mconf-web-rnp`.
